name: 'Semgrep'
author: 'Return To Corporation'
description: 'Easily detect and prevent bugs and anti-patterns in your codebase'
runs:
  using: 'docker'
  image: 'docker://returntocorp/semgrep-action:v1'
inputs:
  config:
    description: |
      Rules and patterns to search for with semgrep.
  slackWebhookURL:
    description: |
      A Slack incoming webhook URL that you want findings posted to.
branding:
  icon: 'align-left'
  color: 'gray-dark'
