name: Builds

on:
  push:
    branches:
      - develop
    tags:
      - "*"

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: docker_tag
      name: Get Docker tag
      run: |
        TAG=${GITHUB_REF}

        TAG=${TAG/refs\/tags\//}
        TAG=${TAG/refs\/heads\//}

        echo "::set-output name=tag::${TAG}"
    - name: publish
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: returntocorp/semgrep-action
        tags: ${{ steps.docker_tag.outputs.tag }}
