name: Linters

on:
  pull_request:
  push:
    branches: [develop]

jobs:
  bento:
    name: Bento
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - id: bento
      name: Bento
      uses: returntocorp/bento-action@v1
      with:
        acceptTermsWithEmail: test@returntocorp.com
        slackWebhookURL: ${{ secrets.BENTO_SLACK_WEBHOOK_URL }}

  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - name: set PY
      run: echo "::set-env name=PY::$(python --version --version | sha256sum | cut -d' ' -f1)"
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v1.0.1

  semgrep:
    name: semgrep with managed policy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: returntocorp/semgrep-action@v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        publishDeployment: ${{ secrets.SEMGREP_APP_DEPLOYMENT }}
