name: Release

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:


jobs:
  # taken from https://github.com/docker/build-push-action/blob/master/UPGRADE.md#tags-with-ref-and-git-labels
  docker:
    name: Publish Docker image
    runs-on: ubuntu-latest
    if: github.repository_owner == 'returntocorp'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get custom tags
        id: custom_tags
        run: |
          CUSTOM_TAGS=""
          if [[ $GITHUB_REF == refs/tags/v1 ]]; then
            CUSTOM_TAGS="stable"
          fi
          echo ::set-output name=custom_tags::${CUSTOM_TAGS}
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1.12.0
        with:
          images: returntocorp/semgrep-action,returntocorp/semgrep-agent
          tag-sha: ${{ github.event_name != 'pull_request' }}
          tag-custom: ${{ steps.custom_tags.outputs.custom_tags }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Cache Docker layers
        uses: actions/cache@v2.1.4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
