jobs:
  semgrep:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - id: semgrep-live-registry-id
      name: semgrep.live Registry ID
      uses: ./
      with:
        config: r/r2c
        slackWebhookURL: ${{ secrets.BENTO_SLACK_WEBHOOK_URL }}
    - id: semgrep-live-id
      name: semgrep.live Rule ID
      uses: ./
      with:
        config: QKP
        slackWebhookURL: ${{ secrets.BENTO_SLACK_WEBHOOK_URL }}
    - id: rule-url
      name: Rule URL
      uses: ./
      with:
        config: https://raw.githubusercontent.com/returntocorp/semgrep-rules/develop/template.yaml
        slackWebhookURL: ${{ secrets.BENTO_SLACK_WEBHOOK_URL }}
    - id: rule-path
      name: Rule Path
      uses: ./
      with:
        config: tests/local_rule.yaml
        slackWebhookURL: ${{ secrets.BENTO_SLACK_WEBHOOK_URL }}
    - id: default-config
      name: Default Config
      uses: ./
      with:
        slackWebhookURL: ${{ secrets.BENTO_SLACK_WEBHOOK_URL }}
name: Self Test
'on':
- pull_request
- push
