jobs:
  semgrep:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - id: semgrep
      name: Semgrep
      uses: ./
      with:
        config: r/r2c
        slackWebhookURL: ${{ secrets.BENTO_SLACK_WEBHOOK_URL }}
name: Self Test
'on':
- pull_request
- push
